use super::{super::super::super::grammar::*, implementation_definition::*, parameter_definition::*};

use {
    compris::{annotate::*, resolve::*},
    depiction::*,
    kutil::std::immutable::*,
    std::collections::*,
};

//
// NotificationDefinition
//

/// A notification definition defines an asynchronous notification or incoming message that can be
/// associated with an interface. The notification is a way for events generated by external
/// implementations to be transmitted to the TOSCA orchestrator. Values can be sent with a
/// notification as notification outputs and can be mapped to node/relationship attributes
/// similarly to the way operation outputs are mapped to attributes. The artifact that the
/// orchestrator is registering with in order to receive the notification is specified using the
/// implementation keyname in a similar way to operations. Artifacts registered to recieve
/// events may be configured by means of parameters provided under the inputs keyname of the
/// notification definition.
///
/// (Documentation copied from
/// [TOSCA specification 2.0](https://docs.oasis-open.org/tosca/TOSCA/v2.0/TOSCA-v2.0.html))
#[derive(Clone, Debug, Default, Depict, Resolve)]
#[depict(tag = tag::source_and_span)]
#[resolve(annotated_parameter=AnnotatedT)]
pub struct NotificationDefinition<AnnotatedT>
where
    AnnotatedT: Annotated + Clone + Default,
{
    /// The optional description string for the associated notification.
    #[resolve]
    #[depict(option, style(string))]
    pub description: Option<ByteString>,

    /// The optional definition of the notification implementation.
    #[resolve(single)]
    #[depict(option, as(depict))]
    pub implementation: Option<ImplementationDefinition<AnnotatedT>>,

    /// The optional map of parameter definitions for notification input values.
    #[resolve]
    #[depict(iter(kv), as(depict), key_style(string))]
    pub inputs: ParameterDefinitions<AnnotatedT>,

    /// The optional map of parameter definitions that specify notification output values. Only
    /// as part of node and relationship type definitions, the output definitions may include
    /// their mappings onto attributes of the node type or relationship type that contains the
    /// definition.
    #[resolve]
    #[depict(iter(kv), as(depict), key_style(string))]
    pub outputs: ParameterDefinitions<AnnotatedT>,

    #[resolve(annotations)]
    #[depict(skip)]
    pub(crate) annotations: StructAnnotations,
}

impl<AnnotatedT> Subentity<Self> for NotificationDefinition<AnnotatedT>
where
    AnnotatedT: 'static + Annotated + Clone + Default,
{
    fn complete(
        &mut self,
        _name: Option<&Name>,
        parent: Option<&Self>,
        parent_namespace: Option<&Namespace>,
        context: &mut CompletionContext,
    ) -> Result<(), ToscaError<WithAnnotations>> {
        complete_subentity_map_field!(input, inputs, self, parent, parent_namespace, true, context);
        complete_subentity_map_field!(output, outputs, self, parent, parent_namespace, true, context);
        complete_subentity_field!(implementation, self, parent, parent_namespace, context);
        Ok(())
    }
}

impl<AnnotatedT> ToNamespace<Self> for NotificationDefinition<AnnotatedT>
where
    AnnotatedT: Annotated + Clone + Default,
{
    fn to_namespace(&self, namespace: Option<&Namespace>) -> Self {
        Self {
            description: self.description.clone(),
            implementation: self.implementation.to_namespace(namespace),
            inputs: self.inputs.to_namespace(namespace),
            outputs: self.outputs.to_namespace(namespace),
            annotations: self.annotations.clone(),
        }
    }
}

//
// NotificationDefinitions
//

/// Map of [NotificationDefinition].
pub type NotificationDefinitions<AnnotatedT> = BTreeMap<Name, NotificationDefinition<AnnotatedT>>;
