#!/bin/bash
set -e

#
# Environment variables:
#
# WASM = release | dev
# Build profile for Wasm code
#

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

cd "$ROOT"

PACKAGE=puccini-plugin-tosca-2_0-functions
TARGET=wasm32-wasip2

if [ "$1" == -r ]; then
	WASM=${WASM:-release}
else
	WASM=${WASM:-dev}
fi

m "building wasm ($WASM)..." "$CYAN"

if [ "$WASM" == release ]; then
	cargo build --package="$PACKAGE" --target="$TARGET" --release
else
    # Note: wild can't link wasm
    # RUSTFLAGS='-Z threads=8 --codegen linker=clang --codegen link-arg=--ld-path=wild' \

	RUSTFLAGS='-Z threads=8' \
	cargo +nightly -Z bindeps build --package="$PACKAGE" --target="$TARGET"
fi
