#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

cd "$ROOT"

# https://stackoverflow.com/a/61417700

RUSTDOCFLAGS="--cfg docsrs" \
cargo +nightly doc --all-features --package=puccini-tosca --package=puccini-floria --package=puccini-csar --package=puccini-plugin-sdk --no-deps --open
