#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

cd "$ROOT"

PACKAGE=puccini-plugin-kubernetes
TARGET=wasm32-wasip2

if [ "$1" == -r ]; then
	PROFILE=release
else
	PROFILE=debug
fi

m "building Wasm ($PROFILE)..." "$CYAN"

if [ "$PROFILE" == release ]; then
    # LTO and stripping debuginfo create smaller Wasm files
    CARGO_PROFILE_RELEASE_LTO=true \
    CARGO_PROFILE_RELEASE_STRIP=debuginfo \
    cargo build --package="$PACKAGE" --target="$TARGET" --release
else
    RUSTFLAGS='-Z threads=8' \
    cargo +nightly build --package="$PACKAGE" --target="$TARGET"
fi

m "creating CSAR..." "$CYAN"

mkdir --parents \
    "$ROOT/examples/online-boutique/artifacts" \
    "$ROOT/examples/csar"

function kconfig () {
    local ARTIFACT=$1
    local JSON=$2
    kubectl config view --raw=true --output=jsonpath="$JSON" \
        | base64 --decode \
        > "$ROOT/examples/online-boutique/artifacts/$ARTIFACT.pem"
}

# kind create cluster

kconfig cacert '{.clusters[0].cluster.certificate-authority-data}'
kconfig cert '{.users[0].user.client-certificate-data}'
kconfig key '{.users[0].user.client-key-data}'

# Another way:
# kubectl get configmap kube-root-ca.crt --output=jsonpath="{['data']['ca\.crt']}" > /tmp/cacert.pem

ln --symbolic --force \
    "$ROOT/target/wasm32-wasip2/$PROFILE/puccini_plugin_kubernetes.wasm" \
    "$ROOT/examples/online-boutique/artifacts/kubernetes-plugin.wasm"

puccini-csar create "$ROOT/examples/online-boutique" "$ROOT/examples/csar/online-boutique.tar.zst"
