#!/bin/bash
set -e

#
# Environment variables:
#
# WASM = release | dev
# Build profile for Wasm code
#

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

cd "$ROOT"

PACKAGE=puccini-plugin-tosca-2_0
TARGET=wasm32-wasip2

if [ "$1" == -r ]; then
	WASM=${WASM:-release}
else
	WASM=${WASM:-dev}
fi

m "building Wasm ($WASM)..." "$CYAN"

if [ "$WASM" == release ]; then
    # LTO and stripping debuginfo create smaller Wasm files
    CARGO_PROFILE_RELEASE_LTO=true \
    CARGO_PROFILE_RELEASE_STRIP=debuginfo \
   	cargo build \
		--package="$PACKAGE" \
		--target="$TARGET" \
		--release
else
    RUSTFLAGS='-Z threads=8' \
	cargo +nightly build \
		--package="$PACKAGE" \
		--target="$TARGET"
fi
