#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

"$HERE/build-python" "$@"

into_python

function example () {
    m "\nexample: $1\n" "$RED"
    "$ROOT/examples/python/$1.py"
}

example readurl
example tosca
example csar
